#!/usr/bin/env sh

if [ "$SEMAPHORE_THREAD_RESULT" != "passed" ]; then exit 1; fi

if [ "$SEMAPHORE_TRIGGER_SOURCE" = "scheduler" ]; then exit; fi

if [ "$BRANCH_NAME" = "master" ]
then
  ci-publish
else
  buho-merge
fi
