#!/usr/bin/env node

var spawn = require('child_process').spawn

var processArguments = require('./processArguments')


const QEMU = require('qemu')+'/bin/qemu-'


var args = processArguments(process.argv.slice(2))

var cpu = args.cpu


// [Hack] Can't be able to use x86_64 as generic x86 64 bits CPU
var toolchainCpu = (cpu === 'nocona')
                 ? 'x86_64'
                 : (args.cpu_family === 'arm') ? 'armv7ve' : cpu

const LD_LIBRARY_PATH = require('nodeos-cross-toolchain')+'/'+toolchainCpu+'-nodeos-linux-'+args.libc+'/lib'

process.env.LD_LIBRARY_PATH = LD_LIBRARY_PATH
var command = QEMU+args.cpu_family
var argv = [LD_LIBRARY_PATH+'/libc.so', 'bin/node']
//var argv = [LD_LIBRARY_PATH+'/libc.so', 'bin/node', '--interactive']
//var command = LD_LIBRARY_PATH+'/libc.so'
//var argv = ['bin/node']

if(args.argv)
  argv = argv.concat(args.argv)

spawn(command, argv, {stdio: 'inherit'})
.on('exit', process.exit.bind(process))
